### ISSUE TITLE
bug: prefetch_relationships changes inventory output — nested traversal through a generic peer resolves empty

### ISSUE THREAD

**Issue by lancamat1** [opsmill/infrahub-ansible#384]
### Ansible Infrahub Collection version

1.7.0

### Ansible version

ansible-core 2.21.3

### Infrahub version

1.10.5, infrahub-sdk 1.23.0

### Python version

3.12.13

### Steps to Reproduce

Requires a schema where a relationship's declared peer is a **generic**, and the concrete
peer kind has fields the generic does not:

- `MyDevice.site` declares peer `LocationGeneric` (a generic)
- the actual peer is `LocationSite`, which has `parent` -> `LocationRegion`
- `LocationGeneric` has neither `name` nor `parent`

```yaml
plugin: opsmill.infrahub.inventory
strict: true
prefetch_relationships: false   # flip this between runs
nodes:
  MyDevice:
    include:
      - name
      - site.name
      - site.parent.name
```

Run `ansible-inventory --list` with the setting `false`, then `true`, and compare.

### Expected Behavior

The same inventory against the same data returns the same hostvars regardless of
`prefetch_relationships`. It reads as a performance option, so it should not change what
resolves.

### Observed Behavior

With `prefetch_relationships: false`:

```
site: {'name': 'site-a', 'parent': {'name': 'region-1'}}
```

With `prefetch_relationships: true` (the default), `parent` comes back empty:

```
site: {'name': 'site-a', 'parent': {}}
```

The peer appears to be cached under the generic kind, which has no `parent`, so the
nested traversal finds nothing and no further fetch happens. Anything built on that
value - composed vars, `keyed_groups` - is then wrong or missing. With `strict: true`
the run aborts:

```
Could not generate group for host device-01 from site.parent.name | lower entry:
object of type 'dict' has no attribute 'name'
```

Measured on the same instance and machine, so the difference is not environmental:

| Inventory | prefetch=false | prefetch=true |
|---|---|---|
| No relationship traversal | 3.1s, all hosts | 3.4s, all hosts |
| Traversing `site.parent` | 87s, all hosts | 40s, **0 hosts** (with `strict: true`) |

The speed-up with prefetch enabled comes from the traversal never happening.

**Comment by BeArchiTek** [comment]
Closing this: the failure is already fixed by #374 (`perf/inventory-projection-and-peer-batching`), which removes the condition rather than repairing it per peer. #386, which targeted this issue directly, is closed alongside — its regression test is being carried over to #374 (details below).

## Verified against a live Infrahub 1.10.5 (infrahub-testcontainers)

#386's integration test was run **verbatim** on #374's head (bbc0d3f), with none of #386's changes to `infrahub_utils.py`:

| code under test | `site.parent.name`, prefetch off / on | many-cardinality analogue* |
|---|---|---|
| `develop` (9c5e9c8) | **2 failed** | **2 failed** |
| #374 (bbc0d3f), unpatched | **2 passed** | **2 passed** |

```
INFRAHUB_TESTING_IMAGE_VER=1.10.5 uv run --no-default-groups --group integration \
    pytest tests/integration/processor/test_generic_peer_traversal.py -m integration
```

\* a probe written for this check, covering the shape neither PR had: `Switch.interfaces` declares the *generic* peer, the concrete `IfaceEth.vlan` -> `Vlan` is the depth-2 hop, traversal `interfaces.vlan.name`. Same result — broken on `develop`, fixed by #374.

## Why #374 fixes it

`PeerWarmer._is_satisfied` in the new `plugins/module_utils/peers.py` treats a nested path whose first segment is a **relationship** on the peer's schema as unsatisfied, so that peer is fetched by id **on its concrete kind** with `prefetch_relationships=True` *before* resolution runs. That store write replaces the generic-shaped entry the host query left behind (the store is last-write-wins by id), so by the time the resolver reads the store the peer already carries the concrete relationship's id, and the depth-2 peer arrived inline with it.

So the store hit is complete in both `prefetch_relationships` modes and for both cardinalities — there is nothing left for a reactive per-peer refetch to repair.

## Coverage

#386's integration test ports cleanly and is the only processor-level test of this shape parametrized on `prefetch_relationships`; #374's own generic-peer coverage is attribute-level (`animals.breed`, with request budgets) plus depth-2 `site.region.name` through the inventory CLI at the default `prefetch_relationships: true`. A follow-up PR against #374's branch adds it, together with the many-cardinality variant above.

One caveat on where that coverage runs: `integration-testcontainers` is gated on `schedule` / `workflow_dispatch`, so these tests guard the nightly build, not PR checks.

**Comment by BeArchiTek** [comment]
Closed as superseded by #374 — see the analysis above.
